### ISSUE TITLE
Redshift explain format not supported

### ISSUE THREAD

**Issue by spazm** [depesz/Pg--Explain#2]
Would you be interested in supporting Redshift format (and accepting a pull request)?

[Amazon Redshift](https://aws.amazon.com/redshift/) was created from a fork of a v8 version of Postgresql.  The [explain syntax](
http://docs.aws.amazon.com/redshift/latest/dg/r_EXPLAIN.html) is similar but different. Primarily the habit of prepending "XN " to most lines as well as items for distributing data between nodes. 

I'm particularly interested in your parser because Redshift explain only supports text mode.

It might not be a huge task to get `Pg::Explain::Node` to support Redshift terms.  Updating the anonymizer code looks more daunting.   

Take these opinions with an appropriately sized grain of salt, I've only spent an hour looking through the code.  I've got the code and tests running locally.

Do you have the `EXPLAIN` queries that created the examples in `t/plans`?  I'd like to regenerate them in redshift for comparison.

### explain.depesz.com

https://explain.depesz.com/s/prf doesn't pick up the values for exclusive, inclusive, etc.

###  Redshift queryplan:
```
XN Window  (cost=1000013470498.49..1000013488354.65 rows=1428493 width=14)
   Partition: os
   ->  XN Sort  (cost=1000013470498.49..1000013474069.72 rows=1428493 width=14)
         Sort Key: os
         ->  XN Network  (cost=0.00..13324463.20 rows=1428493 width=14)
               Distribute
               ->  XN Seq Scan on event  (cost=0.00..13324463.20 rows=1428493 width=14)
                     Filter: ((event_type)::text = 'registration'::text)
```

### Generated from this query:
```
EXPLAIN
    select
      os
      , MIN(event_id) over (
          partition by os
        ) as min_id
    from
      event
    where
      event_type = 'registration'
```

PS.  Thanks for this lovely project and the explain project, complete with containerized mojolicious app and running site!

**Comment by depesz** [comment]
Well, I will not object to accepting a patch, but I'm not really willing to work on it myself.

One thing you need to notice - you wrote "doesn't pick up the values for exclusive, inclusive, etc." - sure it doesn't. the explain output looks like plain "explain query" and exclusive/inclusive are taken only from "explain analyze" output. Extracting cost values from plain explain doesn't seem all that interesting for me.

Having said that - if you (or someone else) would make a patch, I will definitely review it, and if I'll not find any problems with it - I would definitely merge it.

Final thing - no, I don't have source queries, I just ad-hoc queries that show certain operations/constructs when I need them.

**Comment by spazm** [comment]
Thanks for the quick and useful response.

I'll have to try with a proper explain analyze output and see how it goes.
